image: node:slim

stages:
  - build
  - validation
  - release

BuildApi:
  stage: build
  script:
    - cd app
    - yarn
    - yarn build
  artifacts:
    paths:
      - app/node_modules/
      - app/dist/

UnitTests:
  stage: validation
  script:
    - cd app
    - yarn test:coverage
  needs:
    - job: BuildApi
      artifacts: true

CopyPasteDetector:
  stage: validation
  script:
    - cd app
    - yarn basta
  needs:
    - job: BuildApi
      artifacts: true

Linter:
  stage: validation
  script:
    - cd app
    - yarn eslint
  needs:
    - job: BuildApi
      artifacts: true

DeployHeroku:
  stage: release
  script:
    - echo $HEROKU_API_KEY | docker login -u _ registry.heroku.com --password-stdin
    - docker tag latest registry.heroku.com/$APP_NAME/$APP_PROCCESS
    - docker push registry.heroku.com/$APP_NAME/$APP_PROCCESS
  tags:
    - docker
