image: node:slim

stages:
  - build
  - validation

BuildApi:
  stage: build
  script:
    - cd app
    - yarn
    - yarn build
  artifacts:
    paths:
      - node_modules/
      - dist/

UnitTests:
  stage: validation
  script:
    - cd app
    - yarn test:coverage
  needs:
    - job: BuildApi
      artifacts: true

# DeployHeroku:
#   image: lleitep3/node-heroku-cli
#   stage: deploy
#   script:
#     - cd app
#     - yarn build
#     - echo $HEROKU_API_KEY | docker login -u _ registry.heroku.com --password-stdin
#     - heroku container:push web
#     -
#   only:
#     refs:
#       - main