version: "3.4"

services:
  api_todo:
    image: sinform-todo-api
    container_name: sinform-todo-api
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - APP_ENV=production
        - PORT=3000
    environment:
      - APP_ENV=production
      - PORT=3000
    ports:
      - "3010:3000"
    volumes:
      - type: bind
        source: ./app
        target: /app
    networks:
      - minharede

networks:
  minharede:
    external:
      name: minharede
