version: "3.4"

services:
  api_todo:
    image: todo-api
    container_name: todo-api
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - APP_ENV=production
    environment:
      - APP_ENV=local
    ports:
      - "3010:3000"
    volumes:
      - type: bind
        source: ./app
        target: /app
    networks:
      - minharede

networks:
  minharede:
    external:
      name: minharede
